sources += files(
    'Animation.cpp',
    'Animator.cpp',
    'Camera.cpp',
    'Collider.cpp',
    'Collision.cpp',
    'Component.cpp',
    'Game.cpp',
    'GameObject.cpp',
    'InputManager.cpp',
    'Log.cpp',
    'Music.cpp',
    'Observer.cpp',
    'ParticleSystem.cpp',
    'Random.cpp',
    'Rect.cpp',
    'Resources.cpp',
    'Sound.cpp',
    'Sprite.cpp',
    'SpriteRenderer.cpp',
    'State.cpp',
    'Subject.cpp',
    'Text.cpp',
    'TileMap.cpp',
    'TileSet.cpp',
    'Vec2.cpp',
)