name: "sdl"
on: 
    push:
        branches:
            - test

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: libsdl-org/setup-sdl@try-node16
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest
          version-sdl-mixer: 2-latest
      - name: 'Configure and build your project'
        run: |
          cmake -DCMAKE_PREFIX_PATH=${{ steps.sdl.outputs.prefix }} -A Win32 -S . -B build
          cmake --build build --verbose