name: "sdl"
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-32bits:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          version: 2-latest
          version-sdl-image: 2-latest
          version-sdl-mixer: 2-latest
          cmake-arguments: -A Win32
      - name: 'Configure and build your project'
        run: |
          cmake -DCMAKE_PREFIX_PATH=${{ steps.sdl.outputs.prefix }} -A Win32 -S . -B build
          cmake --build build --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: win32
          path: build/Debug/JOGO.exe

  build-64bits:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          version: 2-latest
          version-sdl-image: 2-latest
          version-sdl-mixer: 2-latest
      - name: 'Configure and build your project'
        run: |
          cmake -DCMAKE_PREFIX_PATH=${{ steps.sdl.outputs.prefix }} -S . -B build
          cmake --build build --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: win64
          path: build/Debug/JOGO.exe

  build-linux32:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Deps
      run: sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
    - name: Clean
      run: make clean
    - name: Compile
      run: make
    - uses: actions/upload-artifact@v4
      with:
        name: linux32
        path: JOGO

  release:
    needs: [build-linux32, build-32bits, build-64bits]
    runs-on: ubuntu-latest
    steps:   

    - uses: actions/checkout@v4
    
    - name: Install Deps
      run: sudo apt install zip
    
    - uses: actions/download-artifact@v4
      with:
        name: linux32
    - run: ls -R
    - name: linux pkg
      run: tar -cvf linux32.tar resources JOGO
    
    - uses: actions/download-artifact@v4
      with:
        name: win32
        path: win32
    - name: copy resources to win32
      run: cp -r resources win32
    - name: windows32 pkg
      run: zip -r win32.zip win32

    - uses: actions/download-artifact@v4
      with:
        name: win64
        path: win64
    - name: copy resources to win64
      run: cp -r resources win64
    - name: windows32 pkg
      run: zip -r win64.zip win64

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          linux32.tar
          win32.zip
          win64.zip